updateDocsWhiteList:
  - BUG
  - Chore
  - minor

updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  :tada: Thanks so much for opening your first PR in this project! We really do appreciate your help! :heart:
firstPRMergeComment: >
  Congrats on merging your first pull request in this project! :tada: You're awesome! :metal:
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly! cc/ @surpher
sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @surpher
lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @surpher
