# Always validate the PR title and commits (this is important because release notes are automated and we rely on semantic commit titles)
titleAndCommits: true

# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# You can override the valid types
types:
  - feat
  - feature
  - fix
  - docs
  - doco
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - tech
