#!/usr/bin/env bash

set -eu
set -o pipefail

PATH="$HOME/.cargo/bin:$PATH"
export RUST_BUILD_OUTPUT_DIR="$PROJECT_DIR/build"
mkdir -p $RUST_BUILD_OUTPUT_DIR

cd Submodules/pact-reference/rust/pact_mock_server_ffi && cargo build --release --target-dir $RUST_BUILD_OUTPUT_DIR

cp $RUST_BUILD_OUTPUT_DIR/release/deps/libpact_mock_server_ffi.a "$PROJECT_DIR/Resources/macOS/libpact_mock_server.a"
