#!/usr/bin/env bash

set -eu
set -o pipefail

PATH="$HOME/.cargo/bin:$PATH"

rustup target add x86_64-apple-ios
rustup target add aarch64-apple-ios
cargo install cargo-lipo

cd Submodules/pact-reference/rust/pact_mock_server_ffi && cargo lipo --release

cp "${PROJECT_DIR}/Submodules/pact-reference/rust/target/universal/release/libpact_mock_server_ffi.a" "$PROJECT_DIR/Resources/iOS/libpact_mock_server.a"
