#!/usr/bin/env bash

#  PactSwift
#
#  Created by Marko Justinek on 26/3/20.
#  Copyright © 2020 PACT Foundation. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu

echo "--- 🤖 Linting ${TARGET_NAME} Target Structure..."

#### Variables

#### Expecting for source files to be in ./Sources file (SPM file structure)
TARGET_SRCROOT="${SRCROOT}/Sources"

errors=()

#### Script steps

if [[ ! -z "${INFOPLIST_FILE}" && ! -f "${INFOPLIST_FILE}" ]]; then
    errors+=("error: Could not find Info.plist file "${INFOPLIST_FILE}" for target '${TARGET_NAME}'.")
fi

if [[ ! -d "${TARGET_SRCROOT}" ]]; then
    errors+=("error: Could not find root folder '${TARGET_SRCROOT}' for target '${TARGET_NAME}'.")
fi

if [ ${#errors[@]} -ne 0 ]; then
    for i in "${errors[@]}"; do
        echo $i
    done
    exit 1
fi

echo "--- 👍 Linting ${TARGET_NAME} successful!"
