#!/usr/bin/env bash

set -eu

echo "--- 🤖 Validating project config..."

PROJECT_CONFIG_DIR="${SRCROOT}/Configurations"

### Validate top level project configuration
if [[ ! -d "${PROJECT_CONFIG_DIR}" ]]; then
    echo "error: Could not find 'Configurations' folder for project '${PROJECT_NAME}'."
    exit 1
fi

echo "--- 👍 Project config validated."
