#!/usr/bin/env bash

#  PactSwift
#
#  Created by Marko Justinek on 26/3/20.
#  Copyright © 2020 Itty Bitty Apps Pty Ltd / PACT Foundation. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu

echo "--- 🤖 Validating project config..."

PROJECT_CONFIG_DIR="${SRCROOT}/Configurations"

### Validate top level project configuration
if [[ ! -d "${PROJECT_CONFIG_DIR}" ]]; then
    echo "error: Could not find 'Configurations' folder for project '${PROJECT_NAME}'."
    exit 1
fi

echo "--- 👍 Project config validated."
