#!/usr/bin/env bash

#  PactSwift
#
#  Created by Marko Justinek on 26/3/20.
#  Copyright © 2020 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu

SRCROOT=${SRCROOT:-"."}

if [ $# -ne 2 ]; then
        echo "usage: build_file_list_and_swiftlint project_name swiftlint_yml"
        exit 1
fi

echo "--- 🤖 Linting $SRCROOT/Sources/*.swift"

if which swiftlint >/dev/null; then
        # Run swiftlint (TODO: - swiftlint by iterating through the $1.xcfilelist)
        swiftlint lint "$SRCROOT/Sources"

        # All hunky dory
        echo "--- 👍 .swift files in ./Sources linted"
else
    echo "--- ⚠️ Swiftlint"
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
