#!/usr/bin/env bash

set -euo pipefail

# Scirpt that prepares PactSwift.xcframework

# Properties

TMP_DIR="./.tmp/build-xcframework-spec2"
PRODUCT_NAME="PactSwift"

# Setup

echo "ℹ️  Looking for ${PRODUCT_NAME}.xcodeproj"
if [ ! -d "${PRODUCT_NAME}.xcodeproj" ]; then
    echo "🚨 Run this in the same folder as \"${PRODUCT_NAME}.xcodeproj\"."
    exit 1
fi

echo "ℹ️  Removing existing XCFramework"
rm -fr "../${PRODUCT_NAME}_spec2/PactSwift_spec2.xcframework"
echo "👍  Removed existing XCFramework"

echo "ℹ️  Preparing ${TMP_DIR} folder"
mkdir -p $TMP_DIR
rm -fr $TMP_DIR

# iOS

echo "ℹ️  Building for iOS..."
xcodebuild archive \
    -sdk iphoneos IPHONEOS_DEPLOYMENT_TARGET=12.0 \
    -arch arm64 \
    -scheme "${PRODUCT_NAME}-iOS-spec2" \
    -archivePath "${TMP_DIR}/iphoneos/${PRODUCT_NAME}.xcarchive" \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
    SKIP_INSTALL=NO | xcbeautify

echo "👍  Framework for arm64 built"

echo "ℹ️  Building for iOS Simulator..."
xcodebuild archive \
    -sdk iphonesimulator IPHONEOS_DEPLOYMENT_TARGET=12.0 \
    -arch x86_64 \
    -scheme "${PRODUCT_NAME}-iOS-spec2" \
    -archivePath "${TMP_DIR}/iphonesimulator/${PRODUCT_NAME}.xcarchive" \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
    SKIP_INSTALL=NO | xcbeautify
echo "👍  Framework for iOS Simulator built for x86_64 architecture"

# macOS

echo "ℹ️  Building for macOS..."
xcodebuild archive \
    -sdk macosx MACOSX_DEPLOYMENT_TARGET=10.12 \
    -arch x86_64 \
    -scheme "${PRODUCT_NAME}-macOS-spec2" \
    -archivePath "${TMP_DIR}/macos/${PRODUCT_NAME}.xcarchive" \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
    SKIP_INSTALL=NO | xcbeautify
echo "👍  Framework for macOS built for x86_64 architecture"

# XCFramework

echo "ℹ️  Building XCFramework..."
xcodebuild -create-xcframework -output "../${PRODUCT_NAME}_spec2/${PRODUCT_NAME}_spec2.xcframework" \
    -framework "${TMP_DIR}/iphoneos/${PRODUCT_NAME}.xcarchive/Products/Library/Frameworks/${PRODUCT_NAME}_spec2.framework" \
    -framework "${TMP_DIR}/iphonesimulator/${PRODUCT_NAME}.xcarchive/Products/Library/Frameworks/${PRODUCT_NAME}_spec2.framework" \
    -framework "${TMP_DIR}/macos/${PRODUCT_NAME}.xcarchive/Products/Library/Frameworks/${PRODUCT_NAME}_spec2.framework"

# Cleanup
echo "ℹ️  Removing $TMP_DIR folder..."
rm -fr $TMP_DIR

echo "👍 Done!"
