#!/usr/bin/env bash

set -eu
set -o pipefail

# Checking for Rust
echo "--- 🤖  Checking if Rust is installed..."

if which cargo >/dev/null; then
	echo "👍  cargo installed"
elif command -v ~/.cargo/bin/cargo &> /dev/null; then
	echo "👍  cargo installed in ~/.cargo/bin/"
else
	echo "🚨  Rust not installed"
	echo "ERROR: cargo is required and is not found in `~/.cargo/bin`. Install Rust using either homebrew or follow instructions at https://www.rust-lang.org/tools/install"
	exit 1
fi

# Checking for SwiftLint
if which swiftlint >/dev/null; then
	echo "👍  SwiftLint installed"
else
	echo "⚠️  Swiftlint"
	echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi