#!/usr/bin/env bash

set -eu
set -o pipefail

# Checking for SwiftLint
if which swiftlint >/dev/null; then
    echo "👍  swiftLint installed"
else
    echo "⚠️  Swiftlint"
    echo "warning: SwiftLint not installed, use 'brew install swiftlint' to install it."
fi

# Checking for xcbeautify
if which xcbeautify >/dev/null; then
    echo "👍  xcbeautify installed"
else
    echo "⚠️  xcbeautify"
    echo "warning: xcbeautify not installed, use 'brew install xcbeautify' to install it."
fi
