#!/usr/bin/env bash

set -xeu
set -o pipefail

# Overridable Environment
SIMULATOR_NAME=${SIMULATOR_NAME:-'iPhone 12 Pro'}

# Check for dependencies
if ! [ -x "$(command -v xcbeautify)" ]; then
  echo 'Error: xcbeautify is not installed.' >&2
  exit 1
fi

# Build and test for SPM
swift build -c debug
swift test -Xlinker -LResources/macOS

# Run tests
set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift-iOS -destination "platform=iOS Simulator,name=${SIMULATOR_NAME}" | xcbeautify
set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift-macOS -destination "platform=OS X,arch=x86_64" | xcbeautify
