name: Build

on:
  pull_request:
    types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}_${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_TARGET_PATH: pact-reference

jobs:
  test_ios:
    name: "🤖 Test iOS"
    runs-on: ${{ matrix.host }}

    strategy:
      fail-fast: true
      matrix:
        host: [macos-15, macos-15-intel]
        xcode: [16, 26]
        platform: [ios, macos]

    env:
      SCHEME: ${{ matrix.platform == 'ios' && 'PactSwift-iOS' || 'PactSwift-macOS' }}
      DESTINATION: ${{ matrix.platform == 'ios' && 'platform=iOS Simulator,name=iPhone 16 Pro' || 'arch=x86_64' }}

    steps:
      - name: "🧑‍💻 Checkout repository"
        uses: actions/checkout@v3

      - name: "🏭 Use Xcode ${{ matrix.xcode }}"
        run: |
          XCODE_PATH=$(find /Applications -maxdepth 1 -name "Xcode_${{ matrix.xcode }}*.app" | sort -V | tail -1)
          sudo xcode-select -switch "$XCODE_PATH"

      - name: "🧪 Run tests (xcodebuild)"
        run: |
          set -o pipefail && \
          xcodebuild -resolvePackageDependencies && \
          xcodebuild test \
            -project PactSwift.xcodeproj \
            -scheme "$SCHEME"\
            -destination "$DESTINATION" \
            | xcbeautify

    #   - name: "⚗️ Run tests (swift)"
    #     run: |
    #       swift build
    #       swift test -c release
