name: Build

on:
  pull_request:
    types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
  workflow_dispatch:

env:
  RUST_TARGET_PATH: pact-reference

jobs:
  test_ios:
    name: "🤖 Test iOS"
    runs-on: ${{ matrix.host }}

    strategy:
      fail-fast: true
      matrix:
        host: [macos-14]
        platform: [ios, macos]
        include:
          - platform: ios
            scheme: "PactSwift-iOS"
            destination: "platform=iOS Simulator,name=iPhone 15 Pro"
          - platform: macos
            scheme: "PactSwift-macOS"
            destination: "platform=macOS"
          - host: macos-14
            xcode: 15.3

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    concurrency:
      group: test_${{ matrix.host }}_${{ matrix.xcode }}_${{ matrix.platform }}_${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: "🧑‍💻 Checkout repository"
        uses: actions/checkout@v3

      - name: "🏭 Use Xcode ${{ matrix.xcode }}"
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: "🧪 Run tests (xcodebuild)"
        run: |
          set -o pipefail && \
          xcodebuild -resolvePackageDependencies && \
          xcodebuild test \
            -project PactSwift.xcodeproj \
            -scheme "$SCHEME"\
            -destination "$DESTINATION" \
            | xcbeautify

    #   - name: "⚗️ Run tests (swift)"
    #     run: |
    #       swift build
    #       swift test -c release
